# app-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: customer-api
  labels:
    backstage.io/kubernetes-id: customer-api
spec:
  selector:
    app: customer-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
