# postgres-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    backstage.io/kubernetes-id: customer-api
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
